### PR TITLE
Allow specifying type for response data

### PR DESCRIPTION
**Pull request by awlayton**
Like axios

### CODE REVIEW

**Comment by abalmos** [comment]
This is an improvement, but still a lie. This style is about as good as the `any` type because OADA could return anything. 

I'm not completely against this change, but I'd prefer just returning unknown (JSON isn't much more useful then that as a return value). Then you can either `as` it (so it's clear you don't really know that's the type) or assert it into a type. Axios API is the result of trying to type an API design for JavaScript.

I would also be happy with a second param that takes an assert method to use internally.

**Comment by awlayton** [comment]
I don't really agree with you that it is only that way because of being javascript. Either way when you receive it over the network you cannot be sure of the type unless you use some assertion function. Imo without this change using as as to say what type you want for the data field of the response becomes quite cumbersome. I agree that the default type of it should be unknown.

**Comment by abalmos** [comment]
I suppose were we disagree is that I want using `as` to be cumbersome. Honestly I don't think it should be allowed in strict mode either. If you don't know what it is, you should check it before using it. Otherwise, what's the point?

**Comment by awlayton** [comment]
I'm all for using an assertion when you have one, but I do not always have one. If you add an assertion parameter to the get TS can infer my generic from it.

**Comment by abalmos** [comment]
I'm wondering why you like to use Typescript if your willing to just ignore it here? Particularly with data completely out of your control like an OADA API.

If you don't have an assertion, then you still need code that checks for missing data and handles the error correctly. In that case, an unknown type should be fine, because you'll have checks. 

Like I said, I won't try to stop the merge but I think we would be encouraging bad practice.

**Comment by awlayton** [comment]
TypeScript is great for statically analyzing the flow within your own code, but when it comes to network I/O there are shortcomings. Runtime assertions are great, but when I know what the API _should_ be returning I want to just give the type and then catch any errors from the server responding with something else.

Logically this is no different than using `as`.
But I would rather have:

```ts
const {data: bar} = await conn.get<Bar>({...})
```

than:

```ts
const {data} = await conn.get({...})
const bar = data as Bar
```

In both cases TS just has to believe you that it is a bar. Even in the case of an assertion, TS is just taking your word for it. You could just say:

```ts
function isBar(val: any): asserts val is Bar {
  return
}

**Comment by abalmos** [comment]
True, your validation is only as good as you write it to be, but I suppose that's my point. I want TS to help get it right -- which is all TS is good for anyway. And in this case it can help if you let it.

If you have `get` return `unknown`, then the static analysis can help ensure you are checking for the data that you are accessing. 

`if(data.thing) { ... data.thing ... }` is also a valid typeguard and would be required by TS if `data` was `unknown`

So is something like `if(!data.thing) { throw ...}` . 

Combined with the `?` operator, these checks are not that bad and  give runtime stability.

Sure, using `as` is as bad as using your example assert. However, I still prefer `as` if you are going to try and outsmart TS. In that case, the code is clear: keep your guard up and be careful to wrap everything that accesses the variable in `try`'s, etc because there could be a runtime issue accessing fields.

Just like TS can have bugs, ajv or schema-to-types compiler could have bugs. TS isn't about guarantees like Rust is, but I still don't see the point in purposefully holding it back for the sake of not having to write could that you _should_ be writing.

**Comment by abalmos** [comment]
By should be writing, I mean the code that does this:

> Runtime assertions are great, but when I know what the API _should_ be returning I want to just give the type and then catch any errors from the server responding with something else.

**Comment by awlayton** [comment]
@abalmos how do you feel about exposing a generic type so that asserting the type of the data is not so annyoing?

```typescript
type GetResponse<T = unknown> = SocketResponse & { data: T };

interface Foo {
  a: number;
  b: string;
}

// Now I can assert about the data field without having to specify everything else
const { data: foo } = (await conn.get({ path })) as GetResponse<Foo>;
```

**Comment by abalmos** [comment]
@awlayton That is definitely a type improvement at no cost :+1:  However, I still think the use of `as` is broken. You can't be sure `Foo` really represents the returned data and any "correct" program needs to check it all first. Why not let TS force you into it?

**Comment by awlayton** [comment]
TS can't tell what it is to force you into anything.

**Comment by abalmos** [comment]
Sure it can. It is already. Your adding the `as` statement because TS is complaining that it doesn't know what it is.

**Pull request closed without merging**
