### PR TITLE
V3

### LINKED ISSUE #17: Queuing issue possibly allowing node to suddenly exit without error
After making around 1000 requests concurrently, client's queue handling begins processing, but node exits prior to finishing. Code after the map does not execute.

```
await Promise.map(Object.keys(data), async (key, i) => {                              
  let r = await CONN.put({                       
    path: `/bookmarks/foo/bar/${key}`,
    data: {"foo": i}
  }).catch((err) => {                  
    console.log(err);
  })                            
}, {concurrency: 1000})
.catch(err => {
  console.log(err);
})```

Temporary fix is to keep node alive with a `setInterval`.

### PR DESCRIPTION
**Pull request by awlayton**
All the tests pass. The only major API change is to `watch` (shown in README). The old API for watch still works but it is deprecated.

Instead of defaulting to http, it now tries ALPN to see if h2 is supported. If there is no h2 it defaults to `ws`, otherwise it uses h2.

I rewrote most of the logic connecting the WebSocket back to the individual requests. This should help with lost exceptions and give nicer stack traces. This will hopefully fix #17, though I am not sure yet.

It looks like I added a ton of code if you go by lines, but most of it was new configs or new header comments. The length of actual code should not have changed by much.

### CODE REVIEW

**Review by aultac — APPROVED** [review]

**Comment by aultac** [comment]
Looks good to me, my only request is a feature add which we could do later: to test whether it works in the browser by building it with esbuild and loading some dummy webpage in a browser emulator and making sure it doesn't throw up on loading.

**Comment by awlayton** [comment]
> Looks good to me, my only request is a feature add which we could do later: to test whether it works in the browser by building it with esbuild and loading some dummy webpage in a browser emulator and making sure it doesn't throw up on loading.

I won't promise it works in browser currently, but I took steps to maintain browser support. I used isomorphic libs and such. There will probably be some issue but it should be minor.

**Comment by aultac** [comment]
It didn't work in browsers earlier unless you bundled it with webpack.  Any other bundler failed: snowpack and esbuild were the ones I tried.  This, despite us using clearly isomorphic libs.  It didn't like fetch, if I recall.  That's why I said browser tests were a feature add, I was hoping maybe your fix inadvertently fixed whatever was making all the other bundlers fail :).

**Comment by awlayton** [comment]
> It didn't work in browsers earlier unless you bundled it with webpack.  Any other bundler failed: snowpack and esbuild were the ones I tried.  This, despite us using clearly isomorphic libs.  It didn't like fetch, if I recall.  That's why I said browser tests were a feature add, I was hoping maybe your fix inadvertently fixed whatever was making all the other bundlers fail :).

The issue I remember was eveneitters, not fetch. But I switched v3 to eventemitter3 which is pure js.

**Pull request merged**
